[rules]
[rules.ssh-key]
description = "Detected SSH private key"
regex = '(?i)-----BEGIN[A-Z\s]+(PRIVATE KEY|RSA PRIVATE KEY|OPENSSH PRIVATE KEY)-----'
[rules.env]
description = "Detected .env file"
files = '(?i)\.env.*$'